target 'cheZhiLian' do
platform :ios, '8.0'
pod 'SDWebImage'
pod 'MJExtension'
pod 'AFNetworking'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'ShareSDK3'
pod 'MOBFoundation'
pod 'ShareSDK3/ShareSDKUI'
pod 'ShareSDK3/ShareSDKPlatforms/QQ'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
pod 'FMDB’
end
